configuration_file_version: 1

debug: true

# Default values might be a bit crazy.. They are intended for testing. Change them.

# kick_thresholds field ignores non-numerical characters and only reads three numbers separated, 
#   non-numericals are there only to make configuration file more readable.
#   Use 0 as an amount of seconds when you don't want to kick people.

kick_thresholds:
  - When 81 to 500 players online kick after 60 seconds
  - When 51 to 80  players online kick after 120 seconds
  - When 2  to 50  players online kick after 240 seconds
  - When 1  to 1  players online kick after 3600 seconds  
  
bot_detector:
  # Once the TPS get below acceptable_TPS, the BotDetector starts culling potential lag causer.
  acceptable_TPS: 17.5
  #Once the tps goes below this value, locations start to get logged
  starting_TPS: 18
  # kicking_frequency is how often the bot detector runs in ticks
  kicking_frequency: 1800
  # Whether players get banned for a long time/ until the tick is high again
  long_bans: false
  # Completely disables banning for testing and debugging purposes
  observation_mode: false
  # Length of long ban
  ban_length: 21600000
  # Max locations per player to store while measuring movement patterns
  max_locations: 8
  # Max suspects to consider per Detector round
  max_suspects: 10
  # Baseline movement (in MC blocks) to be considered for bot detection
  min_baseline: 256
  # Maximum scan rounds to "ignore" a player who was previously cleared as a lag source
  max_reprieve: 10
  # Number of BotDetector rounds at good TPS before releasing lag offenders
  release_rounds: 20
  # Scan radius in chunks around location, to check for lag causes
  scan_radius: 4
  # Kick players very close to high-profile lag sources
  kick_nearby: true
  # Radius to consider if kicking nearby players
  kick_nearby_radius: 16
  # Amount of players checked per run
  players_checked_per_run: 1
  # Distance a player needs to move away from a lagsource to not get kicked if he is caught by the system again
  safe_distance: 128
  # Configure the threshold and individual contribution of bound types
  bounds:
    relaxation_factor: 0.1
    threshold: 2.5
    contained: 1.5
    contained_exclude_y: 1.5
    volume_similar: 1.0
    surface_similar: 1.0
    nearly_contained: 0.75
    nearly_contained_exclude_y: 0.75

lag_scanner:
  # Length of time to cache individual chunk results (in milliseconds)
  cache_timeout: 1800000
  # Summation threshold of entity and tile costs for lag flag
  lag_threshold: 400
  # Multiplier of the lag threshold that needs to be exceeded to be banned right away
  extreme_lag_threshold_multiplier: 2.5
  # Reduction Factor (threshold * unload should be < threshold) that must be exceeded to attempt to force unload chunks
  unload_threshold_factor: .25
  # Flag indicating if chunk force unloading on kick should be active
  perform_unload: true
  # Whether the lag scanner should keep scanning if it already determined someone is causing lag
  # to get an exact value how much lag the player is causing
  full_scan: true
  # If a chunk's lag count is below this value, it is considered "normal" and not taken into account for the
  # total lag count calculation
  normal_chunk_value: 100
  # Per tickable block cost 
  tick_block:
    BANNER: 1
    BEACON: 5
    BREWING_STAND: 1
    MOB_SPAWNER: 3
    DROPPER: 3
    JUKEBOX: 1
    NOTE_BLOCK: 1
    SIGN: 1
    HOPPER: 8
    DISPENSER: 3
    FURNACE: 3
    BURNING_FURNACE: 4
    CHEST: 1
    ACTIVATOR_RAIL: 1
    DETECTOR_RAIL: 1
    DAYLIGHT_DETECTOR: 1
    DAYLIGHT_DETECTOR_INVERTED: 1
    DIODE: 1
    DIODE_BLOCK_OFF: 1
    DIODE_BLOCK_ON: 1
    PISTON_BASE: 2
    PISTON_STICKY_BASE: 2
    PISTON_MOVING_PIECE: 8
    PISTON_EXTENSION: 4
    POWERED_RAIL: 1
    REDSTONE_COMPARATOR: 1
    REDSTONE_COMPARATOR_OFF: 1
    REDSTONE_COMPARATOR_ON: 1
    REDSTONE_LAMP_OFF: 1
    REDSTONE_LAMP_ON: 1
    REDSTONE_TORCH_OFF: 1
    REDSTONE_TORCH_ON: 1
    WALL_BANNER: 1
    WALL_SIGN: 1
    SIGN_POST: 1
  # Per tickable entity cost
  tick_entity:
    BAT: 1
    FALLING_BLOCK: 4
    DROPPED_ITEM: 1
    ARMOR_STAND: 1
    BOAT: 2
    CAVE_SPIDER: 1
    CHICKEN: 1
    COW: 1
    CREEPER: 1
    ENDERMAN: 2
    ENDERMITE: 1
    GHAST: 2
    GUARDIAN: 2
    HORSE: 1
    IRON_GOLEM: 2
    MAGMA_CUBE: 2
    MINECART: 1
    MINECART_CHEST: 1
    MINECART_FURNACE: 2
    MINECART_HOPPER: 5
    MINECART_TNT: 3
    MUSHROOM_COW: 1
    OCELOT: 1
    PAINTING: 1
    PIG: 1
    PIG_ZOMBIE: 1
    PRIMED_TNT: 3
    RABBIT: 1
    SHEEP: 1
    SILVERFISH: 2
    SKELETON: 2
    SLIME: 2
    SNOWMAN: 2
    SPIDER: 1
    SQUID: 1
    VILLAGER: 1
    WITCH: 2
    WITHER: 3
    WOLF: 1
    ZOMBIE: 1

# warnings field reads the first number, the rest is text to be sent to a player
warnings:
  - 1 §4AFK Plugin - You'll be kicked in 1 second
  - 2 §4AFK Plugin - You'll be kicked in 2 seconds
  - 3 §4AFK Plugin - You'll be kicked in 3 seconds
  - 4 §4AFK Plugin - You'll be kicked in 4 seconds
  - 5 §4AFK Plugin - You'll be kicked in 5 seconds
  - 10 §4AFK Plugin - You'll be kicked in 10 seconds
  - 60 §4AFK Plugin - You'll be kicked in 1 minute
  - 300 §4AFK Plugin - You'll be kicked in 5 minutes
  - 600 §4AFK Plugin - You'll be kicked in 10 minutes
  - 1800 §4AFK Plugin - You'll be kicked in 30 minutes
  - 3600 §4AFK Plugin - You'll be kicked in 1 hour
  
  
# Yay, rainbows! :)  
kick_message: §cYou §6were §ekicked §adue §9to in§5activity


# Add player Account IDs (UUID) here to exempt them from the AFK checks
immune_accounts: []
